-- Migration SQL file for initial schema synchronization

-- Alter criminals table (already applied in previous step, but keeping for completeness if needed for fresh setup)
-- ALTER TABLE criminals
-- ADD COLUMN first_name varchar(128) NOT NULL,
-- ADD COLUMN last_name varchar(128) NOT NULL,
-- ADD COLUMN photo_url text,
-- ADD COLUMN date_of_birth timestamp,
-- ADD COLUMN address varchar(255),
-- ADD COLUMN email varchar(255),
-- ADD COLUMN phone varchar(50),
-- ADD COLUMN ai_analysis jsonb DEFAULT '{}',
-- ADD COLUMN notes text,
-- ADD COLUMN updated_at timestamp DEFAULT now();

-- Alter evidence table (adjusting based on current database state)
ALTER TABLE evidence
ADD COLUMN IF NOT EXISTS title varchar(255) NOT NULL,
ADD COLUMN IF NOT EXISTS description text,
ADD COLUMN IF NOT EXISTS file_url text NOT NULL,
ADD COLUMN IF NOT EXISTS file_type varchar(50) NOT NULL,
ADD COLUMN IF NOT EXISTS file_size integer NOT NULL,
ADD COLUMN IF NOT EXISTS criminal_id integer,
ADD COLUMN IF NOT EXISTS case_id integer,
ADD COLUMN IF NOT EXISTS ai_summary text,
ADD COLUMN IF NOT EXISTS tags jsonb DEFAULT '[]',
ADD COLUMN IF NOT EXISTS uploaded_at timestamp DEFAULT now(),
ADD COLUMN IF NOT EXISTS uploaded_by text;

-- Add foreign key constraints for evidence table (if not already present)
DO $$ BEGIN
    ALTER TABLE evidence ADD CONSTRAINT evidence_criminal_id_criminals_id_fk FOREIGN KEY (criminal_id) REFERENCES criminals(id) ON DELETE NO ACTION ON UPDATE NO ACTION;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE evidence ADD CONSTRAINT evidence_case_id_cases_id_fk FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE NO ACTION ON UPDATE NO ACTION;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE evidence ADD CONSTRAINT evidence_uploaded_by_users_id_fk FOREIGN KEY (uploaded_by) REFERENCES users(id) ON DELETE NO ACTION ON UPDATE NO ACTION;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

-- Alter cases table
ALTER TABLE cases
ADD COLUMN IF NOT EXISTS status varchar(50) DEFAULT 'open' NOT NULL,
ADD COLUMN IF NOT EXISTS created_by text,
ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT now();

-- Add foreign key constraint for cases table (if not already present)
DO $$ BEGIN
    ALTER TABLE cases ADD CONSTRAINT cases_created_by_users_id_fk FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE NO ACTION ON UPDATE NO ACTION;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

-- Create content_embeddings table
CREATE TABLE IF NOT EXISTS content_embeddings (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id integer NOT NULL,
    content_type varchar(50) NOT NULL,
    embedding text
);

-- Create statutes table
CREATE TABLE IF NOT EXISTS statutes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(255) NOT NULL UNIQUE,
    title varchar(255) NOT NULL,
    description text,
    ai_summary text,
    tags jsonb DEFAULT '[]' NOT NULL,
    created_at timestamp DEFAULT now()
);

-- Create crimes table
CREATE TABLE IF NOT EXISTS crimes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    description text,
    criminal_id integer REFERENCES criminals(id),
    statute_id integer REFERENCES statutes(id),
    created_at timestamp DEFAULT now()
);

-- Create case_evidence table
CREATE TABLE IF NOT EXISTS case_evidence (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id text REFERENCES cases(id),
    evidence_id integer REFERENCES evidence(id),
    added_at timestamp DEFAULT now(),
    added_by text REFERENCES users(id)
);

-- Create tags table
CREATE TABLE IF NOT EXISTS tags (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    category text,
    created_at timestamp DEFAULT now()
);

-- Create evidence_tags table
CREATE TABLE IF NOT EXISTS evidence_tags (
    evidence_id integer REFERENCES evidence(id),
    tag_id integer REFERENCES tags(id),
    assigned_at timestamp DEFAULT now(),
    assigned_by text REFERENCES users(id),
    PRIMARY KEY (evidence_id, tag_id)
);
